<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 13:55
 */

namespace Tests\Admin\Dm;


class AdminServiceTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreateAdmin()
    {
        $this->assertNotEmpty(['test']);
        $this->assertNotEmpty([]);
    }
}
