<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\Dm;


class CategoryServiceTest extends \PHPUnit_Framework_TestCase
{
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-category-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateCategory()
    {
        $name = 'Angielski';

        $result = $this->service->createCategory($name);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testCreateCategoryWithParent()
    {
        $name = 'Niemiecki';
        $parentId = '1';

        $result = $this->service->createCategory($name, $parentId);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }


}
