<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:57
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Repository\CategoryRepository;
use Core\Service\Dm\CategoryAggregate;

class CategoryRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CategoryRepository $repo
     */
    private $repo;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->repo =$c->get('service-category-repository');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetCategoryById()
    {
        $identity = '1';
        $result = $this->repo->getOnIdentity($identity);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\CategoryAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

    public function testGetCategoryByName()
    {
        $name = 'Korepetytor';
        $result = $this->repo->getCategoryByName($name);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\CategoryAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

}
