<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:57
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Repository\CategoryRepository;
use Core\Service\Dm\Repository\LessonRepository;

class LessonRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LessonRepository $repo
     */
    private $repo;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->repo =$c->get('service-lesson-repository');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetLessonById()
    {
        $identity = '1';
        $result = $this->repo->getOnIdentity($identity);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\LessonAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

    public function testGetFreeTermsForDay()
    {
        $date = '2017-01-05';
        $result = $this->repo->getFreeTermsForDay($date);
        $this->assertNotEmpty($result);
        $this->assertNotNull($result);
        var_dump($result);
    }

}
