<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:57
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Repository\RangeRepository;
use Core\Service\Dm\RangeAggregate;

class RangeRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RangeRepository $repo
     */
    private $repo;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->repo =$c->get('service-range-repository');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetRangeById()
    {
        $identity = '1';
        $result = $this->repo->getOnIdentity($identity);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\RangeAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

    public function testGetRangeByName()
    {
        $name = 'liceum';
        $result = $this->repo->getRangeByName($name);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\RangeAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

    public function testGetRangeList()
    {
        $result = $this->repo->getAll();
        $this->assertNotEmpty($result);
        $this->assertNotNull($result);
        var_dump($result);
    }

}
