<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Service\RangeService;

class RangeServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RangeService $service
     */
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-range-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateRange()
    {
        $name = 'studia';

        $result = $this->service->createRange($name);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testChangeRangeName()
    {
        $name = 'studenci';
        $id = '4942bc3bc1a9105ffeeb4dd8576e8b16';

        $result = $this->service->changeRangeName($id, $name);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testRemoveRange()
    {
        $id = '4942bc3bc1a9105ffeeb4dd8576e8b16';

        $result = $this->service->removeRange($id);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

}
