<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Service\TeacherService;

class TeacherServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TeacherService $service
     */
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-teacher-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testAddTeacher()
    {
        $name = 'Mateusz';
        $surname = 'Dudziński';
        $email = 'mateusz@onet.pl';

        $result = $this->service->addTeacher($name, $surname, $email);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testRemoveTeacher()
    {
        $id = '1';

        $result = $this->service->removeTeacher($id);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testChangeTeacherData()
    {

        $name = 'Zbyszek';
        $surname = 'Cichański';
        $city = 'Olszówka';
        $postCode = '34-730';
        $phone = '222222222';
        $categoriesId = ['9c36407a802ceed7301eb87e621e3105', '36966a1402c73cabe1df8e75fb94d724'];
        $driveToStudent = true;
        $rangesId = ['4952a784a90e4d551f2625637b8d8ed0', 'bf8f9e09b4d8c743a7dd53198680e9fe'];

        $result = $this->service->changeTeacherData(
            $name, $surname, $city, $postCode, $phone, $driveToStudent, $categoriesId, $rangesId
        );
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }
}
