<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:57
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Repository\TeacherRepository;
use Core\Service\Dm\TeacherAggregate;

class TeacherRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TeacherRepository $repo
     */
    private $repo;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->repo =$c->get('service-teacher-repository');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetTeacherById()
    {
        $identity = '1';
        $result = $this->repo->getOnIdentity($identity);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\TeacherAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

    public function testGetTeacherByName()
    {
        $email = 'zbyszek@morele.net';
        $result = $this->repo->getTeacherByEmail($email);
        $this->assertNotEmpty($result);
        $this->assertInstanceOf('\Core\Service\Dm\Entity\TeacherAggregate', $result);
        $this->assertNotNull($result);
        var_dump($result);
    }

}
