<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\Dm;

use Core\Service\Dm\Service\TeacherService;

class TeacherServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TeacherService $service
     */
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-teacher-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testAddTeacher()
    {
        $name = 'Mateusz';
        $surname = 'Dudziński';
        $email = 'mateusz@onet.pl';

        $result = $this->service->addTeacher($name, $surname, $email);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }

    public function testRemoveTeacher()
    {
        $id = '1';

        $result = $this->service->removeTeacher($id);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result['status']);
        $this->assertNotEmpty($result);
    }
}
