<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\App;


use Core\Service\App\Command\CategoryCommand;

class CategoryServiceTest extends \PHPUnit_Framework_TestCase
{
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-app-category-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateCategoryWithParent()
    {
        $categoryCommand = new CategoryCommand();
        $categoryCommand->name = 'Francuski';
        $categoryCommand->idParent = '1';

        $result = $this->service->createCategory($categoryCommand);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertInstanceOf('\Core\Core\MessageInterface', $result);
        $this->assertNotEmpty($result);
    }

    public function testCreateCategory()
    {
        $categoryCommand = new CategoryCommand();
        $categoryCommand->name = 'Francuski';

        $result = $this->service->createCategory($categoryCommand);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertInstanceOf('\Core\Core\MessageInterface', $result);
        $this->assertNotEmpty($result);
    }

}
