<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\App;


use Core\Service\App\Command\LessonCommand;
use Core\Service\App\LessonService;

class LessonServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LessonService $service
     */
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-app-lesson-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetFreeTermsForDay()
    {
        $lessonCommand = new LessonCommand();
        $lessonCommand->date = '2017-01-05';
        $message = $this->service->getFreeTermsForDay($lessonCommand);
        var_dump($message);
        $this->assertNotNull($message);
        $this->assertInstanceOf('\Core\Core\MessageInterface', $message);
        $this->assertTrue($message->getStatus());
        $this->assertNotEmpty($message);
    }
}
