<?php
/**
 * Created by PhpStorm.
 * @author: Zbyszek Cichanski
 * Date: 27.12.2016
 * Time: 22:29
 */

namespace Tests\Owner\App;


use Core\Service\App\Command\TeacherCommand;
use Core\Service\App\TeacherService;

class TeacherServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TeacherService $service
     */
    private $service;

    public function setUp()
    {
        $c = require_once "../../../config/container.php";
        $this->service =$c->get('service-app-teacher-service');

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testAddTeacher()
    {
        $teacherCommand = new TeacherCommand();
        $teacherCommand->name = 'Wojtek';
        $teacherCommand->surname = 'Kowalski';
        $teacherCommand->email = 'wojtek@gmail.com';

        $result = $this->service->addTeacher($teacherCommand);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertInstanceOf('\Core\Core\MessageInterface', $result);
        $this->assertTrue($result->getStatus());
        $this->assertNotEmpty($result);
    }


    public function testRemoveTeacher()
    {
        $teacherCommand = new TeacherCommand();
        $teacherCommand->id = 'cc98bcb18d967952bbcbd3b3b6929b0b';

        $result = $this->service->removeTeacher($teacherCommand);
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertInstanceOf('\Core\Core\MessageInterface', $result);
        $this->assertTrue($result->getStatus());
        $this->assertNotEmpty($result);
    }

    public function testGetTeacherList()
    {

        $result = $this->service->getTeacherList();
        var_dump($result);
        $this->assertNotNull($result);
        $this->assertTrue($result->getStatus());
        $this->assertNotEmpty($result);
    }

}
